default: &default
  adapter: postgresql
  pool: 25
  timeout: 10000
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: dj_db_test

production:
  <<: *default
  database: dj_db_production

development:
  <<: *default
  database: dj_db_development